### ISSUE TITLE
TaskSets Sequentially ?

### ISSUE THREAD

**Issue by lucaslain** [johnewart/gearman-ruby#29]
Hello Everyone, 

I'm using gearman-ruby to send a set of 10 tasks that take approximately between 1 and 10 seconds each. When the client calls the "wait()" method, I get a `Gearman::ProtocolError` sometimes

`--ERR> Error: #<Gearman::ProtocolError: Received work_complete when we were expecting JOB_CREATED>`

Is the `Gearman::TaskSet` sending the `Gearman::Task`s  sequentially ? My client broke in a previous run ... maybe it's confusing the results ? 

```
      while @tasks_in_progress.length > 0
        remaining = if end_time
          (t = end_time - Time.now.to_f) > 0 ? t : 0
        else
          nil
        end
        begin
          task = @tasks_in_progress.pop
          if
            @client.submit_job(task, true, remaining)
            @finished_tasks << task
          end
        rescue SocketTimeoutError
          return false
        end

      end
```

**Comment by johnewart** [comment]
Do you have an example of how you're using it? I'll try to reproduce based on your description but that would help it go faster.

**Comment by lucaslain** [comment]
Hello John, 

thank you for your answer. I did some debugging inside the app, and my problem was that I was sending a large taskset that the workers were not able to fulfill in the amount of time specified in `taskset.wait()`

so, 

````
              remaining = if end_time
                            (t = end_time - Time.now.to_f) > 0 ? t : 0
                          else
                            nil
                          end

              p remaining # THIS was nil, so the response was not read

              type, data = connection.read_response(remaining)
```

**Comment by lucaslain** [comment]
Hello John, 

Is gearman allowed to work in parallel (async)? or is it something that only works that way on Ruby implementation? 

I feel that the potential of gearman gets diminished if we execute one task at a time ... 

I've created a fork to test if I can make it work with Eventmachine. I feel like that the only message type that we can't send two at a time is the "SUBMIT_JOB" since it doesn't have a correlation number on the response. But the rest of the messages have the handler. 

Any help on insights on these subject are appreciated! 

Thanks a lot! Lucas.

**Comment by johnewart** [comment]
It will process as many jobs as you have workers available, so if you run 10 workers, you will have 10 jobs executing simultaneously. Each connection is stateful and as a result can only execute one task at a time. If you want to run 10 foreground jobs in parallel you will need 10+ clients requesting work and 10 workers; if you want to execute 10 background jobs you can enqueue as many jobs as you like with one client and run 10 workers to process the work.
